---
- hosts: localhost
  connection: local
  become: true
  strategy: free
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

  tasks:

    ### Check Dependencies And Install Software
    - name: Add Kubernetes Signing Key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        mode: 0644

    - name: Add Kubernetes Repository
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
        state: present

    - name: Update The Apt Cache With Shell
      shell: 'apt-get update'
      args:
        warn: False

    - name: Install Application Packages
      apt:
        name: "{{ packages }}"
        state: present
        force: yes

    ### Copy Configuration And Setup Services
    - name: Disable Active Swap
      shell: 'swapoff -a'

    - name: Disable Swap In Fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: "^.*swap"

    - name: Ensure Bridge Module Is Loaded
      shell: 'modprobe br_netfilter'

    - name: Ensure Overlay Module Is Loaded
      shell: 'modprobe overlay'

    - name: Ensure Bridge Module Is Loaded On Reboot
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        state: present
        create: true
        line: br_netfilter

    - name: Ensure Overlay Module Is Loaded On Reboot
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        state: present
        create: true
        line: overlay

    - name: Enable IPV4 Bridge Visibility For Kubernetes
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Enable IPV6 Bridge Visibility For Kubernetes
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Enable IPV6 Bridge Visibility For Kubernetes
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    ### Post Install Commands
    - name: Ensure Kubernetes Setup Directory Is Present
      file:
        path: /root/k8s-setup
        state: directory
