---
- hosts: localhost
  connection: local
  become: true
  strategy: free

  tasks:

    - name: Untaint All Master Nodes
      shell: 'kubectl --kubeconfig=/etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/master-'
      args:
        warn: False

    - name: Install Tigera Operator For Calico
      shell: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/manifests/tigera-operator.yaml"
      args:
        warn: False

    - name: Wait For CNI Operator To Start
      shell: "kubectl --kubeconfig=/etc/kubernetes/admin.conf wait pods -n tigera-operator -l k8s-app=tigera-operator --for condition=Ready"
      args:
        warn: False

    - name: Apply Calico Configuration
      shell: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -k https://github.com/geoffh1977/kubernetes-gitops-cluster/kubernetes/manifests/overlays/bootstrap/cni/"
      args:
        warn: False

    # Pause With Shell Command (Pause Module Doesn't Work Here)
    - name: Waiting 10 Seconds To Allow CNI To Be Created
      shell: 'sleep 10'

    - name: Wait For Calico Node To Start
      shell: "kubectl --kubeconfig=/etc/kubernetes/admin.conf wait pods -n calico-system -l k8s-app=calico-node --for condition=Ready"
      args:
        warn: False

    - name: Apply GitOps Bootstrap Environment
      shell: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -k https://github.com/geoffh1977/kubernetes-gitops-cluster/kubernetes/manifests/overlays/bootstrap/"
      args:
        warn: False

    # Pause With Shell Command (Pause Module Doesn't Work Here)
    - name: Waiting 5 Seconds To Allow CNI To Be Created
      shell: 'sleep 5'

    - name: Wait For Argo CD To Start
      shell: "kubectl --kubeconfig=/etc/kubernetes/admin.conf wait pods -n argo-cd -l app.kubernetes.io/name=argocd-server --for condition=Ready"
      args:
        warn: False

    - debug:
        msg: "Cluster Has Been Bootstrapped And Started!"
