---
- hosts: localhost
  connection: local
  become: true
  strategy: free

  tasks:

    ### Kubernetes Untaint Master(s)
    - name: Update The Apt Cache With Shell
      shell: "kubectl taint nodes --all node-role.kubernetes.io/master-"
      args:
        warn: False

    ### Activate Bootstrap Environment
    - name: Update The Apt Cache With Shell
      shell: "kubectl apply -k https://github.com/geoffh1977/kubernetes-gitops-cluster/kubernetes/manifests/overlays/bootstrap/"
      args:
        warn: False
