---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
